### ISSUE TITLE
Caps typo on main.cpp line 147

### ISSUE THREAD

**Issue by ludiquechile** [gemi254/PlantStatus-LilyGO-TTGO-Higrow#3]
Build fails on linux
it says:
#include <appPmem.h>
it should:
#include <appPMem.h>

Found the same problem on dependency ConfigAssist, first line of ConfigAssist.cpp should be:
#include "ConfigAssist.h"     // Config assist class
instead of:
#include "configAssist.h"     // Config assist class

That worked to build

**Comment by gemi254** [comment]
Thanks for your suggestion
I fixed the errors and updated to ConfigAssist v2.7.8 that uses yaml for variable definitions..
Adjust your device's config by commenting 
//#define CA_USE_YAML   // Comment to use JSON

at ConfigAssist.h line 7, and compile.

Upload and visit ``http://[device ip]/yaml`` to copy your configuration in yaml format and paste it to 
user_variables.h
Thanks
